# Publish all joint states -------------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

# Position Controllers -----------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j1
  pid: {p: 900, i: 2.5, d: 10}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j2
  pid: {p: 2500, i: 5, d: 20}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j3
  pid: {p: 600, i: 2, d: 5}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j4
  pid: {p: 500, i: 0.5, d: 2}

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j5
  pid: {p: 50, i: 0.5, d: 0.5}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j6
  pid: {p: 50, i: 0.5, d: 0.5}

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: /right/j7
  pid: {p: 8, i: 0.1, d: 0.05}
