- 
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: ft_acceleration }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_position, required: true }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: ft_wrench }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_position, required: true }
